# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import wasalny.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('password2', models.CharField(blank=True, max_length=40)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=wasalny.models.upload_photo)),
            ],
        ),
    ]
